-- ============================================================
--  MathGameApp - MySQL Database Schema (Updated)
--  Questions are randomly generated by the app — NOT stored here.
--  The database only stores users, sessions, and answer history.
-- ============================================================

CREATE DATABASE IF NOT EXISTS mathgameapp;
USE mathgameapp;

-- ============================================================
-- TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    user_id       INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100) UNIQUE,
    role          ENUM('student', 'admin', 'educator') DEFAULT 'student',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login    TIMESTAMP NULL
);

-- ============================================================
-- TABLE: sessions
-- Records each game session a student plays
-- ============================================================
CREATE TABLE IF NOT EXISTS sessions (
    session_id        INT AUTO_INCREMENT PRIMARY KEY,
    user_id           INT NOT NULL,
    mode              ENUM('computational', 'algebra', 'binary') NOT NULL,
    difficulty        ENUM('level1','level2','level3','level4','level5') NOT NULL,
    score             INT DEFAULT 0,
    total_questions   INT DEFAULT 0,
    correct_answers   INT DEFAULT 0,
    time_taken_seconds INT DEFAULT 0,
    played_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================
-- TABLE: answers
-- Records each question attempt within a session.
-- Since questions are generated randomly, we store the
-- question text and correct answer alongside the student's answer.
-- ============================================================
CREATE TABLE IF NOT EXISTS answers (
    answer_id          INT AUTO_INCREMENT PRIMARY KEY,
    session_id         INT NOT NULL,
    question_text      TEXT NOT NULL,
    correct_answer     VARCHAR(255) NOT NULL,
    student_answer     VARCHAR(255),
    is_correct         BOOLEAN DEFAULT FALSE,
    time_taken_seconds INT DEFAULT 0,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

-- ============================================================
-- Default admin account (password: admin123)
-- ============================================================
INSERT INTO users (username, password_hash, full_name, email, role)
VALUES ('admin', SHA2('admin123', 256), 'System Administrator', 'admin@mathgameapp.com', 'admin');
