-- ============================================================
--  MathGameApp - SQL Server Database Schema
--  Questions are randomly generated by the app — NOT stored here.
--  The database only stores users, sessions, and answer history.
-- ============================================================

-- Create database if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'mathgameapp')
BEGIN
    CREATE DATABASE mathgameapp;
END
GO

USE mathgameapp;
GO

-- ============================================================
-- TABLE: users
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
    CREATE TABLE [dbo].[users] (
        user_id       INT IDENTITY(1,1) PRIMARY KEY,
        username      VARCHAR(50)  NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL,
        full_name     VARCHAR(100) NOT NULL,
        email         VARCHAR(100) UNIQUE,
        role          VARCHAR(50) DEFAULT 'student' CHECK (role IN ('student', 'admin', 'educator')),
        created_at    DATETIME DEFAULT GETDATE(),
        last_login    DATETIME NULL
    );
END
GO

-- ============================================================
-- TABLE: sessions
-- Records each game session a student plays
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[sessions]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
    CREATE TABLE [dbo].[sessions] (
        session_id        INT IDENTITY(1,1) PRIMARY KEY,
        user_id           INT NOT NULL,
        mode              VARCHAR(50) NOT NULL CHECK (mode IN ('computational', 'algebra', 'binary')),
        difficulty        VARCHAR(50) NOT NULL CHECK (difficulty IN ('level1','level2','level3','level4','level5')),
        score             INT DEFAULT 0,
        total_questions   INT DEFAULT 0,
        correct_answers   INT DEFAULT 0,
        time_taken_seconds INT DEFAULT 0,
        played_at         DATETIME DEFAULT GETDATE(),
        FOREIGN KEY (user_id) REFERENCES [dbo].[users](user_id) ON DELETE CASCADE
    );
END
GO

-- ============================================================
-- TABLE: answers
-- Records each question attempt within a session.
-- Since questions are generated randomly, we store the
-- question text and correct answer alongside the student's answer.
-- ============================================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[answers]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
    CREATE TABLE [dbo].[answers] (
        answer_id          INT IDENTITY(1,1) PRIMARY KEY,
        session_id         INT NOT NULL,
        question_text      NVARCHAR(MAX) NOT NULL,
        correct_answer     VARCHAR(255) NOT NULL,
        student_answer     VARCHAR(255),
        is_correct         BIT DEFAULT 0,
        time_taken_seconds INT DEFAULT 0,
        FOREIGN KEY (session_id) REFERENCES [dbo].[sessions](session_id) ON DELETE CASCADE
    );
END
GO

-- ============================================================
-- Default admin account (password: admin123)
-- ============================================================
IF NOT EXISTS (SELECT * FROM [dbo].[users] WHERE username = 'admin')
BEGIN
    INSERT INTO [dbo].[users] (username, password_hash, full_name, email, role)
    VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'System Administrator', 'admin@mathgameapp.com', 'admin');
END
GO
